version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATASOURCE_PASSWORD
      - MYSQL_DATABASE=$DATASOURCE_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: